version: "3"
services:
  redis:
    image: redis:4
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis:
  mongo:
